services:
  sinmalos-minemeld:
    build:
      context: ./minemeld
      args:
        CREATE_AUTOSIGNED_SSL_CERTS: "true"
    container_name: sinmalos-minemeld
    image: sinmalos-minemeld
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    restart: always
    volumes:
      - SinMalos-MM-local:/opt/minemeld/local
      - SinMalos-MM-logs:/opt/minemeld/log

volumes:
  SinMalos-MM-local:
  SinMalos-MM-logs: