nodes:
  Miner-REYES-CCN-CERT-Inbound:
    inputs: []
    output: true
    prototype: REYES-CCN-CERT.Miner-REYES-CCN-CERT-Inbound
  Miner-REYES-CCN-CERT-Outbound:
    inputs: []
    output: true
    prototype: REYES-CCN-CERT.Miner-REYES-CCN-CERT-Outbound
  REYES-CCN-CERT-Inbound:
    indicator_types:
    - IPv4
    inputs:
    - Reyes-aggregatorIPv4Generic
    node_type: output
    output: false
    prototype: REYES-CCN-CERT.REYES-CCN-CERT-Inbound
  REYES-CCN-CERT-Outbound:
    indicator_types:
    - IPv4
    inputs:
    - Reyes-aggregatorIPv4Generic
    node_type: output
    output: false
    prototype: REYES-CCN-CERT.REYES-CCN-CERT-Outbound
  SinMalos-MultiSource:
    inputs: []
    output: true
    prototype: SinMalos.SinMalos-MultiSource
  SinMalos-ALL:
    inputs: []
    output: true
    prototype: SinMalos.SinMalos-ALL
  SM-MultiSource-HC:
    indicator_types:
    - IPv4
    - IPv6
    inputs:
    - SinMalos-aggregatorIPv4Generic
    node_type: output
    output: false
    prototype: SinMalos.SinMalos-MultiSource-HC
  SM-ALL-MC:
    indicator_types:
    - IPv4
    - IPv6
    inputs:
    - SinMalos-aggregatorIPv4Generic
    node_type: output
    output: false
    prototype: SinMalos.SinMalos-ALL-MC
  SinMalos-aggregatorIPv4Generic:
    inputs:
    - SinMalos-ALL
    - SinMalos-MultiSource
    - wl-SinMalos-WhiteList-IPv4
    output: true
    prototype: stdlib.aggregatorIPv4Generic
  Reyes-aggregatorIPv4Generic:
    inputs:
    - wl-SinMalos-WhiteList-IPv4
    - Miner-REYES-CCN-CERT-Inbound
    - Miner-REYES-CCN-CERT-Outbound
    output: true
    prototype: stdlib.aggregatorIPv4Generic
  wl-SinMalos-WhiteList-IPv4:
    inputs: []
    output: true
    prototype: stdlib.listIPv4Generic